onelake:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('ONELAKE_DUCKDB', '../data/warehouse/onelake.duckdb') }}"
      threads: 4
      schema: main
      settings:
        timezone: UTC
    ci:
      type: duckdb
      path: "{{ env_var('ONELAKE_CI_DUCKDB', '../data/warehouse/ci.duckdb') }}"
      threads: 4
      schema: main
      settings:
        timezone: UTC
    fabric:
      type: fabric
      server: "crzlr2mpr3ievehmtvofnskjge-opzbo7htdboezlgnvbxisla4yu.datawarehouse.fabric.microsoft.com"
      port: 1433
      database: "wh_onelake"
      schema: dbo
      authentication: CLI
      encrypt: true
      trust_cert: false
      threads: 4
      retries: 2
